### PR TITLE
Update openapi-snippet package

### PR DESCRIPTION
**Pull request by RolphH**
Bumped version for openapi-snippet to the latest as it has some fixes

### CODE REVIEW

**Comment by RolphH** [comment]
@KarolNet any change to get this merged?

**Comment by KarolNet** [comment]
Hi, sorry for the long delay.

**Comment by RolphH** [comment]
Thanks @KarolNet can you also bump the version on npm?

**Comment by KarolNet** [comment]
Hi, npm has been updated.

**Pull request merged**
